#pragma warning disable 0,

using Twinning.AssistantPlus;
using System.Text.Json.Serialization;

namespace Twinning.AssistantPlus.Utility {

	[JsonSerializable(typeof(Object))]
	[JsonSerializable(typeof(Boolean))]
	[JsonSerializable(typeof(Integer))]
	[JsonSerializable(typeof(Floater))]
	[JsonSerializable(typeof(String))]
	[JsonSerializable(typeof(List<Object>))]
	[JsonSerializable(typeof(Dictionary<String, Object>))]
	[JsonSerializable(typeof(SettingData), TypeInfoPropertyName = "Twinning_AssistantPlus_SettingData")]
	[JsonSerializable(typeof(CustomThemeMode), TypeInfoPropertyName = "Twinning_AssistantPlus_CustomThemeMode")]
	[JsonSerializable(typeof(CustomThemeBackdrop), TypeInfoPropertyName = "Twinning_AssistantPlus_CustomThemeBackdrop")]
	[JsonSerializable(typeof(ModuleType), TypeInfoPropertyName = "Twinning_AssistantPlus_ModuleType")]
	[JsonSerializable(typeof(ModuleLauncherConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_ModuleLauncherConfiguration")]
	[JsonSerializable(typeof(ModuleLauncherCategory), TypeInfoPropertyName = "Twinning_AssistantPlus_ModuleLauncherCategory")]
	[JsonSerializable(typeof(ModuleLauncherSetting), TypeInfoPropertyName = "Twinning_AssistantPlus_ModuleLauncherSetting")]
	[JsonSerializable(typeof(View.CoreTaskWorker.Setting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreTaskWorker_Setting")]
	[JsonSerializable(typeof(View.CoreTaskWorker.Configuration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreTaskWorker_Configuration")]
	[JsonSerializable(typeof(View.CoreCommandSender.Setting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreCommandSender_Setting")]
	[JsonSerializable(typeof(View.CoreCommandSender.PresetConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreCommandSender_PresetConfiguration")]
	[JsonSerializable(typeof(List<View.CoreCommandSender.PresetConfiguration>), TypeInfoPropertyName = "List__Twinning_AssistantPlus_View_CoreCommandSender_PresetConfiguration")]
	[JsonSerializable(typeof(View.CoreCommandSender.ArgumentType), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreCommandSender_ArgumentType")]
	[JsonSerializable(typeof(View.CoreCommandSender.ArgumentConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreCommandSender_ArgumentConfiguration")]
	[JsonSerializable(typeof(View.CoreCommandSender.MethodConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreCommandSender_MethodConfiguration")]
	[JsonSerializable(typeof(View.CoreCommandSender.MethodGroupConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreCommandSender_MethodGroupConfiguration")]
	[JsonSerializable(typeof(List<View.CoreCommandSender.MethodGroupConfiguration>), TypeInfoPropertyName = "List__Twinning_AssistantPlus_View_CoreCommandSender_MethodGroupConfiguration")]
	[JsonSerializable(typeof(View.CoreCommandSender.Configuration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreCommandSender_Configuration")]
	[JsonSerializable(typeof(View.CoreResourceShipper.Setting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreResourceShipper_Setting")]
	[JsonSerializable(typeof(View.CoreResourceShipper.PresetConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreResourceShipper_PresetConfiguration")]
	[JsonSerializable(typeof(List<View.CoreResourceShipper.PresetConfiguration>), TypeInfoPropertyName = "List__Twinning_AssistantPlus_View_CoreResourceShipper_PresetConfiguration")]
	[JsonSerializable(typeof(View.CoreResourceShipper.FilterType), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreResourceShipper_FilterType")]
	[JsonSerializable(typeof(View.CoreResourceShipper.FilterConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreResourceShipper_FilterConfiguration")]
	[JsonSerializable(typeof(View.CoreResourceShipper.OptionConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreResourceShipper_OptionConfiguration")]
	[JsonSerializable(typeof(View.CoreResourceShipper.OptionGroupConfiguration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreResourceShipper_OptionGroupConfiguration")]
	[JsonSerializable(typeof(List<View.CoreResourceShipper.OptionGroupConfiguration>), TypeInfoPropertyName = "List__Twinning_AssistantPlus_View_CoreResourceShipper_OptionGroupConfiguration")]
	[JsonSerializable(typeof(View.CoreResourceShipper.Configuration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_CoreResourceShipper_Configuration")]
	[JsonSerializable(typeof(View.PopcapAnimationViewer.Setting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapAnimationViewer_Setting")]
	[JsonSerializable(typeof(View.PopcapAnimationViewer.Configuration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapAnimationViewer_Configuration")]
	[JsonSerializable(typeof(Model.PopcapAnimationModel.Rectangle), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapAnimationModel_Rectangle")]
	[JsonSerializable(typeof(Model.PopcapAnimationModel.LayerRemove), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapAnimationModel_LayerRemove")]
	[JsonSerializable(typeof(Model.PopcapAnimationModel.LayerAppend), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapAnimationModel_LayerAppend")]
	[JsonSerializable(typeof(Model.PopcapAnimationModel.LayerChange), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapAnimationModel_LayerChange")]
	[JsonSerializable(typeof(Model.PopcapAnimationModel.Frame), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapAnimationModel_Frame")]
	[JsonSerializable(typeof(Model.PopcapAnimationModel.Sprite), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapAnimationModel_Sprite")]
	[JsonSerializable(typeof(Model.PopcapAnimationModel.Image), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapAnimationModel_Image")]
	[JsonSerializable(typeof(Model.PopcapAnimationModel.Animation), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapAnimationModel_Animation")]
	[JsonSerializable(typeof(View.PopcapReflectionDescriptor.Setting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapReflectionDescriptor_Setting")]
	[JsonSerializable(typeof(View.PopcapReflectionDescriptor.Configuration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapReflectionDescriptor_Configuration")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.PrimitiveType), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_PrimitiveType")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.CompositeType), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_CompositeType")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.FixedValue), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_FixedValue")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.NamedValue), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_NamedValue")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.ExtraValue), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_ExtraValue")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.FixedObject), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_FixedObject")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.AddressedFixedObject), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_AddressedFixedObject")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.ValueDescriptor), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_ValueDescriptor")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.EnumerationDescriptor), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_EnumerationDescriptor")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.PropertyDescriptor), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_PropertyDescriptor")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.ObjectDescriptor), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_ObjectDescriptor")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.DescriptorArchive), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_DescriptorArchive")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.DescriptorMap), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_DescriptorMap")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.DataObject), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_DataObject")]
	[JsonSerializable(typeof(Model.PopcapReflectionModel.DataArchive), TypeInfoPropertyName = "Twinning_AssistantPlus_Model_PopcapReflectionModel_DataArchive")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.Setting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_Setting")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.Configuration), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_Configuration")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PackageVersion), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PackageVersion")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PackageCompression), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PackageCompression")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PackageCategory), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PackageCategory")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PackageManifestType), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PackageManifestType")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PackageManifest), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PackageManifest")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.Variable), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_Variable")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.ResourceType), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_ResourceType")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.ResourceCategory), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_ResourceCategory")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.DummyResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_DummyResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.GeneralResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_GeneralResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.TextureResourcePropertySpriteResource), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_TextureResourcePropertySpriteResource")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.TextureResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_TextureResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.SpecialRtonResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_SpecialRtonResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.SpecialPtxResourcePropertySpriteResource), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_SpecialPtxResourcePropertySpriteResource")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.SpecialPtxResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_SpecialPtxResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.SpecialPamResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_SpecialPamResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.SpecialPopfxResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_SpecialPopfxResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.SpecialWemResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_SpecialWemResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.SpecialBnkResourceProperty), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_SpecialBnkResourceProperty")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.ResourceSetting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_ResourceSetting")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.GroupSetting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_GroupSetting")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PartSetting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PartSetting")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PackageConversionItem), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PackageConversionItem")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PackageConversion), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PackageConversion")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.PackageSetting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_PackageSetting")]
	[JsonSerializable(typeof(View.PopcapPackageBuilder.ProjectSetting), TypeInfoPropertyName = "Twinning_AssistantPlus_View_PopcapPackageBuilder_ProjectSetting")]
	public partial class JsonSourceGenerationContext : JsonSerializerContext {
	}

}
