#pragma warning disable 0,
// ReSharper disable

using AssistantPlus;
using System.Text.Json.Serialization;

namespace AssistantPlus.Utility {

	[JsonSerializable(typeof(Object))]
	[JsonSerializable(typeof(Boolean))]
	[JsonSerializable(typeof(Integer))]
	[JsonSerializable(typeof(Floater))]
	[JsonSerializable(typeof(String))]
	[JsonSerializable(typeof(List<Object>))]
	[JsonSerializable(typeof(Dictionary<String, Object>))]
	[JsonSerializable(typeof(SettingData), TypeInfoPropertyName = "AssistantPlus_SettingData")]
	[JsonSerializable(typeof(CustomThemeMode), TypeInfoPropertyName = "AssistantPlus_CustomThemeMode")]
	[JsonSerializable(typeof(CustomThemeColor), TypeInfoPropertyName = "AssistantPlus_CustomThemeColor")]
	[JsonSerializable(typeof(CustomThemeBackdrop), TypeInfoPropertyName = "AssistantPlus_CustomThemeBackdrop")]
	[JsonSerializable(typeof(CustomThemeSetting), TypeInfoPropertyName = "AssistantPlus_CustomThemeSetting")]
	[JsonSerializable(typeof(CustomWindowPosition), TypeInfoPropertyName = "AssistantPlus_CustomWindowPosition")]
	[JsonSerializable(typeof(CustomWindowSize), TypeInfoPropertyName = "AssistantPlus_CustomWindowSize")]
	[JsonSerializable(typeof(CustomWindowSetting), TypeInfoPropertyName = "AssistantPlus_CustomWindowSetting")]
	[JsonSerializable(typeof(ModuleType), TypeInfoPropertyName = "AssistantPlus_ModuleType")]
	[JsonSerializable(typeof(ModuleLauncherConfiguration), TypeInfoPropertyName = "AssistantPlus_ModuleLauncherConfiguration")]
	[JsonSerializable(typeof(ModuleLauncherCategory), TypeInfoPropertyName = "AssistantPlus_ModuleLauncherCategory")]
	[JsonSerializable(typeof(ModuleLauncherSetting), TypeInfoPropertyName = "AssistantPlus_ModuleLauncherSetting")]
	[JsonSerializable(typeof(View.ModdingWorker.Setting), TypeInfoPropertyName = "AssistantPlus_View_ModdingWorker_Setting")]
	[JsonSerializable(typeof(View.CommandSender.Setting), TypeInfoPropertyName = "AssistantPlus_View_CommandSender_Setting")]
	[JsonSerializable(typeof(View.ResourceShipper.Setting), TypeInfoPropertyName = "AssistantPlus_View_ResourceShipper_Setting")]
	[JsonSerializable(typeof(View.AnimationViewer.Setting), TypeInfoPropertyName = "AssistantPlus_View_AnimationViewer_Setting")]
	[JsonSerializable(typeof(View.ReflectionDescriptor.Setting), TypeInfoPropertyName = "AssistantPlus_View_ReflectionDescriptor_Setting")]
	[JsonSerializable(typeof(View.PackageBuilder.Setting), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_Setting")]
	[JsonSerializable(typeof(GameAnimationModel.Rectangle), TypeInfoPropertyName = "AssistantPlus_GameAnimationModel_Rectangle")]
	[JsonSerializable(typeof(GameAnimationModel.LayerRemove), TypeInfoPropertyName = "AssistantPlus_GameAnimationModel_LayerRemove")]
	[JsonSerializable(typeof(GameAnimationModel.LayerAppend), TypeInfoPropertyName = "AssistantPlus_GameAnimationModel_LayerAppend")]
	[JsonSerializable(typeof(GameAnimationModel.LayerChange), TypeInfoPropertyName = "AssistantPlus_GameAnimationModel_LayerChange")]
	[JsonSerializable(typeof(GameAnimationModel.Frame), TypeInfoPropertyName = "AssistantPlus_GameAnimationModel_Frame")]
	[JsonSerializable(typeof(GameAnimationModel.Sprite), TypeInfoPropertyName = "AssistantPlus_GameAnimationModel_Sprite")]
	[JsonSerializable(typeof(GameAnimationModel.Image), TypeInfoPropertyName = "AssistantPlus_GameAnimationModel_Image")]
	[JsonSerializable(typeof(GameAnimationModel.Animation), TypeInfoPropertyName = "AssistantPlus_GameAnimationModel_Animation")]
	[JsonSerializable(typeof(GameReflectionModel.PrimitiveType), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_PrimitiveType")]
	[JsonSerializable(typeof(GameReflectionModel.CompositeType), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_CompositeType")]
	[JsonSerializable(typeof(GameReflectionModel.FixedValue), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_FixedValue")]
	[JsonSerializable(typeof(GameReflectionModel.NamedValue), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_NamedValue")]
	[JsonSerializable(typeof(GameReflectionModel.ExtraValue), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_ExtraValue")]
	[JsonSerializable(typeof(GameReflectionModel.FixedObject), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_FixedObject")]
	[JsonSerializable(typeof(GameReflectionModel.AddressedFixedObject), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_AddressedFixedObject")]
	[JsonSerializable(typeof(GameReflectionModel.ValueDescriptor), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_ValueDescriptor")]
	[JsonSerializable(typeof(GameReflectionModel.EnumerationDescriptor), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_EnumerationDescriptor")]
	[JsonSerializable(typeof(GameReflectionModel.PropertyDescriptor), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_PropertyDescriptor")]
	[JsonSerializable(typeof(GameReflectionModel.ObjectDescriptor), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_ObjectDescriptor")]
	[JsonSerializable(typeof(GameReflectionModel.DescriptorArchive), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_DescriptorArchive")]
	[JsonSerializable(typeof(GameReflectionModel.DescriptorMap), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_DescriptorMap")]
	[JsonSerializable(typeof(GameReflectionModel.DataObject), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_DataObject")]
	[JsonSerializable(typeof(GameReflectionModel.DataArchive), TypeInfoPropertyName = "AssistantPlus_GameReflectionModel_DataArchive")]
	[JsonSerializable(typeof(View.CommandSender.PresetConfiguration), TypeInfoPropertyName = "AssistantPlus_View_CommandSender_PresetConfiguration")]
	[JsonSerializable(typeof(List<View.CommandSender.PresetConfiguration>), TypeInfoPropertyName = "List__AssistantPlus_View_CommandSender_PresetConfiguration")]
	[JsonSerializable(typeof(View.CommandSender.ArgumentType), TypeInfoPropertyName = "AssistantPlus_View_CommandSender_ArgumentType")]
	[JsonSerializable(typeof(View.CommandSender.ArgumentConfiguration), TypeInfoPropertyName = "AssistantPlus_View_CommandSender_ArgumentConfiguration")]
	[JsonSerializable(typeof(View.CommandSender.MethodConfiguration), TypeInfoPropertyName = "AssistantPlus_View_CommandSender_MethodConfiguration")]
	[JsonSerializable(typeof(View.CommandSender.MethodGroupConfiguration), TypeInfoPropertyName = "AssistantPlus_View_CommandSender_MethodGroupConfiguration")]
	[JsonSerializable(typeof(List<View.CommandSender.MethodGroupConfiguration>), TypeInfoPropertyName = "List__AssistantPlus_View_CommandSender_MethodGroupConfiguration")]
	[JsonSerializable(typeof(View.ResourceShipper.PresetConfiguration), TypeInfoPropertyName = "AssistantPlus_View_ResourceShipper_PresetConfiguration")]
	[JsonSerializable(typeof(List<View.ResourceShipper.PresetConfiguration>), TypeInfoPropertyName = "List__AssistantPlus_View_ResourceShipper_PresetConfiguration")]
	[JsonSerializable(typeof(View.ResourceShipper.FilterType), TypeInfoPropertyName = "AssistantPlus_View_ResourceShipper_FilterType")]
	[JsonSerializable(typeof(View.ResourceShipper.FilterConfiguration), TypeInfoPropertyName = "AssistantPlus_View_ResourceShipper_FilterConfiguration")]
	[JsonSerializable(typeof(View.ResourceShipper.OptionConfiguration), TypeInfoPropertyName = "AssistantPlus_View_ResourceShipper_OptionConfiguration")]
	[JsonSerializable(typeof(View.ResourceShipper.OptionGroupConfiguration), TypeInfoPropertyName = "AssistantPlus_View_ResourceShipper_OptionGroupConfiguration")]
	[JsonSerializable(typeof(List<View.ResourceShipper.OptionGroupConfiguration>), TypeInfoPropertyName = "List__AssistantPlus_View_ResourceShipper_OptionGroupConfiguration")]
	[JsonSerializable(typeof(View.PackageBuilder.PackageVersion), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PackageVersion")]
	[JsonSerializable(typeof(View.PackageBuilder.PackageCompression), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PackageCompression")]
	[JsonSerializable(typeof(View.PackageBuilder.PackageCategory), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PackageCategory")]
	[JsonSerializable(typeof(View.PackageBuilder.PackageManifestType), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PackageManifestType")]
	[JsonSerializable(typeof(View.PackageBuilder.PackageManifest), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PackageManifest")]
	[JsonSerializable(typeof(View.PackageBuilder.Variable), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_Variable")]
	[JsonSerializable(typeof(View.PackageBuilder.ResourceType), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_ResourceType")]
	[JsonSerializable(typeof(View.PackageBuilder.ResourceCategory), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_ResourceCategory")]
	[JsonSerializable(typeof(View.PackageBuilder.DummyResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_DummyResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.GeneralResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_GeneralResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.TextureResourcePropertySpriteResource), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_TextureResourcePropertySpriteResource")]
	[JsonSerializable(typeof(View.PackageBuilder.TextureResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_TextureResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.SpecialRtonResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_SpecialRtonResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.SpecialPtxResourcePropertySpriteResource), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_SpecialPtxResourcePropertySpriteResource")]
	[JsonSerializable(typeof(View.PackageBuilder.SpecialPtxResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_SpecialPtxResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.SpecialPamResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_SpecialPamResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.SpecialPopfxResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_SpecialPopfxResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.SpecialWemResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_SpecialWemResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.SpecialBnkResourceProperty), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_SpecialBnkResourceProperty")]
	[JsonSerializable(typeof(View.PackageBuilder.ResourceSetting), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_ResourceSetting")]
	[JsonSerializable(typeof(View.PackageBuilder.GroupSetting), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_GroupSetting")]
	[JsonSerializable(typeof(View.PackageBuilder.PartSetting), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PartSetting")]
	[JsonSerializable(typeof(View.PackageBuilder.PackageConversionItem), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PackageConversionItem")]
	[JsonSerializable(typeof(View.PackageBuilder.PackageConversion), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PackageConversion")]
	[JsonSerializable(typeof(View.PackageBuilder.PackageSetting), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_PackageSetting")]
	[JsonSerializable(typeof(View.PackageBuilder.ProjectSetting), TypeInfoPropertyName = "AssistantPlus_View_PackageBuilder_ProjectSetting")]
	public partial class JsonSourceGenerationContext : JsonSerializerContext {
	}

}
