include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unnecessary_cast: ignore
    unnecessary_this: ignore
    unnecessary_string_interpolations: ignore
    unnecessary_brace_in_string_interps: ignore
    avoid_init_to_null: ignore
    prefer_final_fields: ignore
    prefer_is_empty: ignore
    empty_catches: ignore
    sort_child_properties_last: ignore
linter:
  rules:
    prefer_single_quotes: true
    prefer_function_declarations_over_variables: false
    prefer_interpolation_to_compose_strings: false
    use_build_context_synchronously: false
