name: assistant
version: 173.0.0+173
environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter
  ffi: 2.2.0
  win32: 5.15.0
  async: 2.13.1
  collection: 1.19.1
  stack_trace: 1.12.1
  decimal: 3.2.4
  json5: 0.8.2
  vdf: 1.1.0
  archive: 4.0.9
  provider: 6.1.5+1
  material_symbols_icons: 4.2928.1
  single_child_two_dimensional_scroll_view: 0.1.0
  super_drag_and_drop: 0.9.1
  dynamic_color: 1.8.1
  window_manager: 0.5.1
  app_links: 7.0.0
  flutter_local_notifications: 21.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
flutter:
  uses-material-design: true
  assets:
    - asset/
