#pragma once

#include "core/utility/exception/source_location.hpp"
#include "core/utility/exception/exception.hpp"
#include "core/utility/exception/simple_exception.hpp"
#include "core/utility/exception/special_exception.hpp"
#include "core/utility/exception/base_exception/utility.hpp"
#include "core/utility/exception/base_exception/exception_message.hpp"
#include "core/utility/exception/base_exception/base_exception.hpp"

#include "core/utility/trait/base.hpp"
#include "core/utility/trait/category.hpp"
#include "core/utility/trait/template_instance.hpp"
#include "core/utility/trait/object.hpp"
#include "core/utility/trait/builtin.hpp"
#include "core/utility/trait/enum.hpp"
#include "core/utility/trait/range.hpp"
#include "core/utility/trait/package/type_package.hpp"
#include "core/utility/trait/package/value_package.hpp"
#include "core/utility/trait/callable.hpp"
#include "core/utility/trait/reflection/string.hpp"
#include "core/utility/trait/reflection/information.hpp"
#include "core/utility/trait/reflection/field.hpp"
#include "core/utility/trait/reflection/utility.hpp"
#include "core/utility/trait/generalization.hpp"
#include "core/utility/trait/trait.hpp"

#include "core/utility/base_wrapper/base.hpp"
#include "core/utility/base_wrapper/boolean.hpp"
#include "core/utility/base_wrapper/number.hpp"
#include "core/utility/base_wrapper/character.hpp"
#include "core/utility/base_wrapper/byte.hpp"
#include "core/utility/base_wrapper/pointer.hpp"
#include "core/utility/base_wrapper/null_pointer.hpp"
#include "core/utility/base_wrapper/wrapper.hpp"

#include "core/utility/misc/allocator.hpp"

#include "core/utility/null.hpp"

#include "core/utility/container/wrapper/wrapper_view.hpp"
#include "core/utility/container/wrapper/wrapper.hpp"
#include "core/utility/container/optional/optional_view.hpp"
#include "core/utility/container/optional/optional.hpp"
#include "core/utility/container/optional/null_optional.hpp"
#include "core/utility/container/variant/variant.hpp"
#include "core/utility/container/variant/enumerable_variant.hpp"
#include "core/utility/container/any/any.hpp"
#include "core/utility/container/tuple/tuple.hpp"

#include "core/utility/range/range_wrapper.hpp"
#include "core/utility/range/number_iterator.hpp"
#include "core/utility/range/number_range.hpp"
#include "core/utility/range/algorithm.hpp"

#include "core/utility/container/list/list_view.hpp"
#include "core/utility/container/list/list.hpp"
#include "core/utility/container/map/map_view.hpp"
#include "core/utility/container/map/map.hpp"
#include "core/utility/container/array/array.hpp"
#include "core/utility/container/static_array/static_array.hpp"
#include "core/utility/container/stream/stream_method.hpp"
#include "core/utility/container/stream/stream_view.hpp"

#include "core/utility/misc/math.hpp"
#include "core/utility/misc/enum.hpp"
#include "core/utility/misc/fourcc.hpp"
#include "core/utility/misc/number_variant.hpp"
#include "core/utility/misc/finalizer.hpp"

#include "core/utility/misc/byte_series/container.hpp"
#include "core/utility/misc/byte_series/utility.hpp"
#include "core/utility/misc/byte_series/stream_adapter.hpp"
#include "core/utility/misc/byte_series/stream.hpp"
#include "core/utility/misc/byte_series/stream_adapter_utility.hpp"

#include "core/utility/misc/character_series/type.hpp"
#include "core/utility/misc/character_series/container.hpp"
#include "core/utility/misc/character_series/stream_adapter.hpp"
#include "core/utility/misc/character_series/stream.hpp"

#include "core/utility/string/basic_string_adapter.hpp"
#include "core/utility/string/basic_string_view.hpp"
#include "core/utility/string/basic_string.hpp"
#include "core/utility/string/basic_static_string.hpp"
#include "core/utility/string/string.hpp"
#include "core/utility/string/encoding.hpp"
#include "core/utility/string/format.hpp"
#include "core/utility/string/parser.hpp"

#include "core/utility/image/size.hpp"
#include "core/utility/image/channel.hpp"
#include "core/utility/image/pixel.hpp"
#include "core/utility/image/basic_bitmap_view.hpp"
#include "core/utility/image/basic_bitmap.hpp"
#include "core/utility/image/bitmap.hpp"
#include "core/utility/image/file/png.hpp"

#include "core/utility/data/json/value_adapter.hpp"
#include "core/utility/data/json/value.hpp"
#include "core/utility/data/json/value_adapter_utility.hpp"
#include "core/utility/data/json/parser.hpp"

#include "core/utility/data/xml/node.hpp"
#include "core/utility/data/xml/parser.hpp"

#include "core/utility/script/js/value_adapter.hpp"
#include "core/utility/script/js/handler.hpp"
#include "core/utility/script/js/js.hpp"
#include "core/utility/script/js/utility.hpp"

#include "core/utility/file_system/path.hpp"
#include "core/utility/file_system/file_system.hpp"

#include "core/utility/system/windows.hpp"
#include "core/utility/system/posix.hpp"
#include "core/utility/system/system.hpp"

#include "core/utility/misc/bitset.hpp"
#include "core/utility/misc/kv_pair.hpp"
#include "core/utility/misc/2d_type.hpp"
#include "core/utility/misc/padding_block.hpp"
#include "core/utility/misc/string_block.hpp"
#include "core/utility/misc/thread.hpp"

#include "core/utility/support/byte_stream.hpp"
#include "core/utility/support/character_stream.hpp"
#include "core/utility/support/string.hpp"
#include "core/utility/support/json.hpp"
#include "core/utility/support/js.hpp"
#include "core/utility/support/stl.hpp"
#include "core/utility/support/fmt.hpp"

namespace TwinKleS::Core {
}
