# common condition definition

# system
if(M_system_windows)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_system_windows)
endif()
if(M_system_linux)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_system_linux)
endif()
if(M_system_macos)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_system_macos)
endif()
if(M_system_android)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_system_android)
endif()
if(M_system_ios)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_system_ios)
endif()

# compiler
if(M_compiler_msvc)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_compiler_msvc)
endif()
if(M_compiler_clang)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_compiler_clang)
endif()

# build
if(M_build_debug)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_build_debug)
endif()
if(M_build_release)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_build_release)
endif()
if(M_build_release_debug)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_build_release_debug)
endif()
if(M_build_release_minimum)
	target_compile_definitions(${PROJECT_NAME} PRIVATE M_build_release_minimum)
endif()
